// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyR9XTBMi-ezzIjmCWZxlQRmYMXkAH-24',
    appId: '1:536668195309:web:d19ba4cbf571b315cc3fe4',
    messagingSenderId: '536668195309',
    projectId: 'instagram-app-d0c1a',
    authDomain: 'instagram-app-d0c1a.firebaseapp.com',
    storageBucket: 'instagram-app-d0c1a.firebasestorage.app',
    measurementId: 'G-97KVH4YRPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6heUqB3ZlbDDFrTlMTZbrn-1KdcbyGq8',
    appId: '1:536668195309:android:5ece6512deb5db24cc3fe4',
    messagingSenderId: '536668195309',
    projectId: 'instagram-app-d0c1a',
    storageBucket: 'instagram-app-d0c1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf9GW_F2p4e_QBLuNwLHxuqP9yHEHSvn8',
    appId: '1:536668195309:ios:bd2c68c9b2522b14cc3fe4',
    messagingSenderId: '536668195309',
    projectId: 'instagram-app-d0c1a',
    storageBucket: 'instagram-app-d0c1a.firebasestorage.app',
    iosBundleId: 'com.example.instagramApp',
  );
}
